### ISSUE TITLE
PqResultImpl::wait_for_data() undeclared variables

### ISSUE THREAD

**Issue by harvey131** [r-dbi/RPostgres#202]
When building the latest version from master, I have errors that the 'fd_set', 'FD_SET', 'FD_ZERO', 'input', and 'select' variables were not declared in the PqResultImpl::wait_for_data() function.

R 3.5.1 (r open)
Rtools version 3.5.0.4

**Comment by krlmlr** [comment]
Thanks, confirmed. Full output from AppVeyor:

```
* installing *source* package 'RPostgres' ...
** libs

*** arch - i386
"c:/R/bin/i386/Rscript.exe" "../tools/winlibs.R"
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"c:/R/include" -DNDEBUG -I../windows/libpq-9.5.2/include -I"c:/RLibrary/BH/include" -I"c:/RLibrary/plogr/include" -I"c:/RLibrary/Rcpp/include"        -O2 -Wall  -mtune=generic -c DbColumn.cpp -o DbColumn.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"c:/R/include" -DNDEBUG -I../windows/libpq-9.5.2/include -I"c:/RLibrary/BH/include" -I"c:/RLibrary/plogr/include" -I"c:/RLibrary/Rcpp/include"        -O2 -Wall  -mtune=generic -c DbColumnDataSource.cpp -o DbColumnDataSource.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"c:/R/include" -DNDEBUG -I../windows/libpq-9.5.2/include -I"c:/RLibrary/BH/include" -I"c:/RLibrary/plogr/include" -I"c:/RLibrary/Rcpp/include"        -O2 -Wall  -mtune=generic -c DbColumnDataSourceFactory.cpp -o DbColumnDataSourceFactory.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"c:/R/include" -DNDEBUG -I../windows/libpq-9.5.2/include -I"c:/RLibrary/BH/include" -I"c:/RLibrary/plogr/include" -I"c:/RLibrary/Rcpp/include"        -O2 -Wall  -mtune=generic -c DbColumnStorage.cpp -o DbColumnStorage.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"c:/R/include" -DNDEBUG -I../windows/libpq-9.5.2/include -I"c:/RLibrary/BH/include" -I"c:/RLibrary/plogr/include" -I"c:/RLibrary/Rcpp/include"        -O2 -Wall  -mtune=generic -c DbConnection.cpp -o DbConnection.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"c:/R/include" -DNDEBUG -I../windows/libpq-9.5.2/include -I"c:/RLibrary/BH/include" -I"c:/RLibrary/plogr/include" -I"c:/RLibrary/Rcpp/include"        -O2 -Wall  -mtune=generic -c DbDataFrame.cpp -o DbDataFrame.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"c:/R/include" -DNDEBUG -I../windows/libpq-9.5.2/include -I"c:/RLibrary/BH/include" -I"c:/RLibrary/plogr/include" -I"c:/RLibrary/Rcpp/include"        -O2 -Wall  -mtune=generic -c DbResult.cpp -o DbResult.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"c:/R/include" -DNDEBUG -I../windows/libpq-9.5.2/include -I"c:/RLibrary/BH/include" -I"c:/RLibrary/plogr/include" -I"c:/RLibrary/Rcpp/include"        -O2 -Wall  -mtune=generic -c PqColumnDataSource.cpp -o PqColumnDataSource.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"c:/R/include" -DNDEBUG -I../windows/libpq-9.5.2/include -I"c:/RLibrary/BH/include" -I"c:/RLibrary/plogr/include" -I"c:/RLibrary/Rcpp/include"        -O2 -Wall  -mtune=generic -c PqColumnDataSourceFactory.cpp -o PqColumnDataSourceFactory.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"c:/R/include" -DNDEBUG -I../windows/libpq-9.5.2/include -I"c:/RLibrary/BH/include" -I"c:/RLibrary/plogr/include" -I"c:/RLibrary/Rcpp/include"        -O2 -Wall  -mtune=generic -c PqDataFrame.cpp -o PqDataFrame.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"c:/R/include" -DNDEBUG -I../windows/libpq-9.5.2/include -I"c:/RLibrary/BH/include" -I"c:/RLibrary/plogr/include" -I"c:/RLibrary/Rcpp/include"        -O2 -Wall  -mtune=generic -c PqResultImpl.cpp -o PqResultImpl.o
PqResultImpl.cpp: In member function 'void PqResultImpl::wait_for_data()':
PqResultImpl.cpp:474:3: error: 'fd_set' was not declared in this scope
   fd_set input;
   ^
PqResultImpl.cpp:480:12: error: 'input' was not declared in this scope
   FD_ZERO(&input);
            ^
PqResultImpl.cpp:480:17: error: 'FD_ZERO' was not declared in this scope
   FD_ZERO(&input);
                 ^
PqResultImpl.cpp:481:24: error: 'FD_SET' was not declared in this scope
   FD_SET(socket, &input);
                        ^
PqResultImpl.cpp:489:52: error: 'select' was not declared in this scope
     ret = select(nfds, &input, NULL, NULL, &timeout);
                                                    ^
make: *** [c:/R/etc/i386/Makeconf:215: PqResultImpl.o] Error 1
ERROR: compilation failed for package 'RPostgres'
* removing 'C:/projects/rpostgres/RPostgres.Rcheck/RPostgres'
In R CMD INSTALL
```

**Comment by krlmlr** [comment]
@zozlak: `fd_set` introduced in #193 seems to be undefined on Windows, at least with libpq 9.5.2 which is currently used here (https://github.com/rwinlib/libpq, thanks @jeroen for maintaining the Windows libs). Could you please take a look?

**Comment by zozlak** [comment]
They are provided by the socket-related library and not by the libpq. It looks like on Windows it's the winsock library (https://docs.microsoft.com/en-us/windows/desktop/api/winsock/ns-winsock-fd_set).

**Comment by jeroen** [comment]
Maybe you need something like this in the file where you use the `fd_set`:

```c
#ifdef _WIN32
#include <winsock2.h>
#endif
```

**Comment by krlmlr** [comment]
Testing now: https://ci.appveyor.com/project/r-dbi/rpostgres/builds/21298350

**Comment by zozlak** [comment]
And maybe also an additional flag for the linker like `-lwinsock2` (or whatever the proper name is)...

**Comment by krlmlr** [comment]
The first attempt in c2cbf5d failed (from `00install.out` in the artifacts of the AppVeyor build):

```
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"c:/R/include" -DNDEBUG -I../windows/libpq-9.5.2/include -I"c:/RLibrary/BH/include" -I"c:/RLibrary/plogr/include" -I"c:/RLibrary/Rcpp/include"        -O2 -Wall  -mtune=generic -c PqResultImpl.cpp -o PqResultImpl.o
In file included from C:/Rtools/mingw_32/i686-w64-mingw32/include/combaseapi.h:155:0,
                 from C:/Rtools/mingw_32/i686-w64-mingw32/include/objbase.h:14,
                 from C:/Rtools/mingw_32/i686-w64-mingw32/include/ole2.h:17,
                 from C:/Rtools/mingw_32/i686-w64-mingw32/include/wtypes.h:12,
                 from C:/Rtools/mingw_32/i686-w64-mingw32/include/winscard.h:10,
                 from C:/Rtools/mingw_32/i686-w64-mingw32/include/windows.h:97,
                 from C:/Rtools/mingw_32/i686-w64-mingw32/include/winsock2.h:23,
                 from PqResultImpl.cpp:9:
C:/Rtools/mingw_32/i686-w64-mingw32/include/objidlbase.h:864:18: error: macro "Realloc" requires 3 arguments, but only 2 given
         SIZE_T cb) = 0;
                  ^
C:/Rtools/mingw_32/i686-w64-mingw32/include/objidlbase.h:864:22: error: 'Realloc' declared as a 'virtual' field
         SIZE_T cb) = 0;
                      ^
In file included from c:/R/include/R.h:91:0,
                 from c:/RLibrary/Rcpp/include/Rcpp/r/headers.h:63,
                 from c:/RLibrary/Rcpp/include/RcppCommon.h:29,
                 from c:/RLibrary/Rcpp/include/Rcpp.h:27,
                 from pch.h:1,
                 from PqResultImpl.cpp:1:
c:/R/include/R_ext/RS.h:74:37: error: expected identifier before '(' token
 #define Free(p)        (R_chk_free( (void *)(p) ), (p) = NULL)
                                     ^
c:/R/include/R_ext/RS.h:74:47: error: 'parameter' declared as function returning a function
 #define Free(p)        (R_chk_free( (void *)(p) ), (p) = NULL)
                                               ^
c:/R/include/R_ext/RS.h:74:50: error: expected ')' before ',' token
 #define Free(p)        (R_chk_free( (void *)(p) ), (p) = NULL)
                                                  ^
c:/R/include/R_ext/RS.h:74:37: error: expected identifier before '(' token
 #define Free(p)        (R_chk_free( (void *)(p) ), (p) = NULL)
                                     ^
c:/R/include/R_ext/RS.h:74:47: error: 'parameter' declared as function returning a function
 #define Free(p)        (R_chk_free( (void *)(p) ), (p) = NULL)
                                               ^
c:/R/include/R_ext/RS.h:74:50: error: expected ')' before ',' token
 #define Free(p)        (R_chk_free( (void *)(p) ), (p) = NULL)
                                                  ^
make: *** [c:/R/etc/i386/Makeconf:215: PqResultImpl.o] Error 1
ERROR: compilation failed for package 'RPostgres'
* removing 'C:/projects/rpostgres/RPostgres.Rcheck/RPostgres'
In R CMD INSTALL
```

It looks much easier to disable this functionality for Windows.

**Comment by jeroen** [comment]
Try adding `-DSTRICT_R_HEADERS`  to `PKG_CPPFLAGS` in `Makevars.win`.

**Comment by jeroen** [comment]
That seems to have worked.

**Comment by krlmlr** [comment]
Thanks a lot! I haven't tested if the new `check_interrupts` setting actually works on Windows, though.
